export const ROUTES = {
  home: '/',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  emailVerificationSuccess: '/email-verification-success',
  unauthorized: '/unauthorized',
  sessionExpired: '/session-expired',
  loading: '/loading',
  jobs: '/jobs',
  jobDetails: '/jobs/:id',
  candidateDashboard: '/candidate/dashboard',
  companyDashboard: '/company/dashboard',
  adminDashboard: '/admin/dashboard',
  adminUsers: '/admin/users',
  adminCompanies: '/admin/companies',
  adminJobs: '/admin/jobs',
  adminApplications: '/admin/applications',
  adminCatalog: '/admin/catalog',
  adminAnalytics: '/admin/analytics',
  adminSettings: '/admin/settings',
  profile: '/profile',
  resume: '/resume',
  notFound: '*',
};
